version: "3.8"
services:
  gameapptestauto:
    image: kellucd/snakegarands:latest
    build: .
    container_name: randsauto
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
      